using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using XMS.Core;

namespace URLRewriter
{
    public class APIClient
    {
        //public static  XMS.Portal.Common.ICommonService CommenService
        //{
        //    get
        //    {
        //        return Container.Instance.Resolve<XMS.Portal.Common.ICommonService>();
        //    }
        //}
    }
}
